image: xdtianyu/docker:openjdk8
before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - source /opt/setup-android-sdk.sh
  - source /opt/setup-android-ndk.sh
  - openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv -in release.jks.enc -out release.jks -d
stages:
  - build
  - deploy
build:
  stage: build
  script:
    - ./gradlew assembleDebug
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - "**/build/outputs/apk/**/*.apk"
      - "**/build/outputs/mapping/release/mapping.txt"
    expire_in: 1 day
release:
  stage: deploy
  script:
    - cp app/build/outputs/apk/release/*.apk .
    - cp app/build/outputs/mapping/release/mapping.txt .
  artifacts:
    paths:
      - "*.apk"
      - "mapping.txt"
  only:
    - tags
